// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityAction string

const (
	ActivityActionLogin                ActivityAction = "login"
	ActivityActionProfileUpdate        ActivityAction = "profile_update"
	ActivityActionLogoutAll            ActivityAction = "logout_all"
	ActivityActionAccountDelete        ActivityAction = "account_delete"
	ActivityActionFavoriteAdd          ActivityAction = "favorite_add"
	ActivityActionFavoriteRemove       ActivityAction = "favorite_remove"
	ActivityActionCommentCreate        ActivityAction = "comment_create"
	ActivityActionCommentDelete        ActivityAction = "comment_delete"
	ActivityActionStatReportCreate     ActivityAction = "stat_report_create"
	ActivityActionStatReportUpdate     ActivityAction = "stat_report_update"
	ActivityActionStatReportMove       ActivityAction = "stat_report_move"
	ActivityActionStatReportHide       ActivityAction = "stat_report_hide"
	ActivityActionStatReportUnhide     ActivityAction = "stat_report_unhide"
	ActivityActionPendingReportCreate  ActivityAction = "pending_report_create"
	ActivityActionPendingReportApprove ActivityAction = "pending_report_approve"
	ActivityActionPendingReportReject  ActivityAction = "pending_report_reject"
	ActivityActionReportFileView       ActivityAction = "report_file_view"
	ActivityActionSittingCreate        ActivityAction = "sitting_create"
	ActivityActionVotingOpen           ActivityAction = "voting_open"
	ActivityActionVotingUpdate         ActivityAction = "voting_update"
	ActivityActionVotingClose          ActivityAction = "voting_close"
	ActivityActionVoteCutoffSet        ActivityAction = "vote_cutoff_set"
	ActivityActionVoteCast             ActivityAction = "vote_cast"
	ActivityActionVotingRequestCreate  ActivityAction = "voting_request_create"
	ActivityActionVotingRequestCancel  ActivityAction = "voting_request_cancel"
	ActivityActionVotingRequestReject  ActivityAction = "voting_request_reject"
	ActivityActionAdminGrant           ActivityAction = "admin_grant"
	ActivityActionAdminRevoke          ActivityAction = "admin_revoke"
	ActivityActionLogsExport           ActivityAction = "logs_export"
	ActivityActionLogsDelete           ActivityAction = "logs_delete"
	ActivityActionLogsClear            ActivityAction = "logs_clear"
	ActivityActionLogsRetentionDelete  ActivityAction = "logs_retention_delete"
	ActivityActionLogsArchive          ActivityAction = "logs_archive"
)

func (e *ActivityAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityAction(s)
	case string:
		*e = ActivityAction(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityAction: %T", src)
	}
	return nil
}

type NullActivityAction struct {
	ActivityAction ActivityAction
	Valid          bool // Valid is true if ActivityAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityAction) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityAction), nil
}

type ArchiveStatus string

const (
	ArchiveStatusRunning   ArchiveStatus = "running"
	ArchiveStatusSucceeded ArchiveStatus = "succeeded"
	ArchiveStatusFailed    ArchiveStatus = "failed"
)

func (e *ArchiveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArchiveStatus(s)
	case string:
		*e = ArchiveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ArchiveStatus: %T", src)
	}
	return nil
}

type NullArchiveStatus struct {
	ArchiveStatus ArchiveStatus
	Valid         bool // Valid is true if ArchiveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArchiveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ArchiveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArchiveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArchiveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArchiveStatus), nil
}

type ImportStatus string

const (
	ImportStatusRunning   ImportStatus = "running"
	ImportStatusSucceeded ImportStatus = "succeeded"
	ImportStatusFailed    ImportStatus = "failed"
)

func (e *ImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImportStatus(s)
	case string:
		*e = ImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ImportStatus: %T", src)
	}
	return nil
}

type NullImportStatus struct {
	ImportStatus ImportStatus
	Valid        bool // Valid is true if ImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImportStatus), nil
}

type JobStatus string

const (
	JobStatusSucceeded JobStatus = "succeeded"
	JobStatusFailed    JobStatus = "failed"
	JobStatusSkipped   JobStatus = "skipped"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus
	Valid     bool // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type ReportStatus string

const (
	ReportStatusPending  ReportStatus = "pending"
	ReportStatusApproved ReportStatus = "approved"
	ReportStatusRejected ReportStatus = "rejected"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus
	Valid        bool // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

type StatSource string

const (
	StatSourceDirect      StatSource = "direct"
	StatSourceTranscribed StatSource = "transcribed"
)

func (e *StatSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatSource(s)
	case string:
		*e = StatSource(s)
	default:
		return fmt.Errorf("unsupported scan type for StatSource: %T", src)
	}
	return nil
}

type NullStatSource struct {
	StatSource StatSource
	Valid      bool // Valid is true if StatSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatSource) Scan(value interface{}) error {
	if value == nil {
		ns.StatSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatSource), nil
}

type VotingRequestStatus string

const (
	VotingRequestStatusOpen      VotingRequestStatus = "open"
	VotingRequestStatusFulfilled VotingRequestStatus = "fulfilled"
	VotingRequestStatusRejected  VotingRequestStatus = "rejected"
	VotingRequestStatusCancelled VotingRequestStatus = "cancelled"
)

func (e *VotingRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VotingRequestStatus(s)
	case string:
		*e = VotingRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VotingRequestStatus: %T", src)
	}
	return nil
}

type NullVotingRequestStatus struct {
	VotingRequestStatus VotingRequestStatus
	Valid               bool // Valid is true if VotingRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVotingRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VotingRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VotingRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVotingRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VotingRequestStatus), nil
}

type ActivityLog struct {
	ID        int64
	UserID    *int64
	Action    ActivityAction
	Metadata  []byte
	Ip        *netip.Addr
	CreatedAt time.Time
}

type AssessmentKind struct {
	ID          int16
	Code        string
	LabelKo     string
	LabelFormat string
	Numbered    bool
	MaxNumber   *int16
	SortOrder   int16
	IsActive    bool
}

type CatalogImport struct {
	ID              int64
	StartedAt       time.Time
	FinishedAt      *time.Time
	Status          ImportStatus
	SourceLabel     *string
	CoursesTotal    *int32
	CoursesAdded    *int32
	CoursesUnlisted *int32
	OfferingsTotal  *int32
	SectionsTotal   *int32
	Error           *string
}

type CatalogSection struct {
	ID            int64
	CourseID      int64
	Year          int16
	Semester      int16
	CourseNumber  string
	LectureNumber string
	DepartmentID  int32
	ClassTime     []byte
}

type College struct {
	Name      string
	SortOrder int16
	IsActive  bool
}

type Comment struct {
	ID        int64
	CourseID  int64
	UserID    int64
	Body      string
	CreatedAt time.Time
}

type ContentVersion struct {
	Singleton bool
	N         int64
}

type Course struct {
	ID           int64
	Title        string
	InstructorID int32
	IdentityKey  string
	LegacyKey    *string
	SearchText   string
	IsListed     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CourseOffering struct {
	CourseID     int64
	Year         int16
	Semester     int16
	DepartmentID int32
}

type Department struct {
	ID   int32
	Name string
}

type ExamSitting struct {
	ID               int64
	CourseID         int64
	KindID           int16
	Number           *int16
	Year             int16
	Semester         int16
	VotingOpenedAt   *time.Time
	VotingClosesAt   *time.Time
	VotingEndedAt    *time.Time
	VotesCountedFrom *time.Time
	CreatedAt        time.Time
}

type Favorite struct {
	UserID    int64
	CourseID  int64
	CreatedAt time.Time
}

type Instructor struct {
	ID            int32
	Name          string
	IsPlaceholder bool
}

type JobRun struct {
	ID         int64
	Name       string
	StartedAt  time.Time
	FinishedAt time.Time
	Status     JobStatus
	Affected   int32
	Error      *string
}

type LogArchiveRun struct {
	ID          int64
	StartedAt   time.Time
	FinishedAt  *time.Time
	Status      ArchiveStatus
	Cutoff      *time.Time
	Format      string
	RowCount    *int32
	FirstID     *int64
	LastID      *int64
	DriveFileID *string
	Error       *string
}

type PendingReport struct {
	ID          int64
	CourseID    int64
	KindID      int16
	Number      *int16
	Year        int16
	Semester    int16
	UploaderID  int64
	Nickname    string
	FileKey     string
	FileName    string
	ContentType string
	ByteSize    int32
	Sha256      string
	Status      ReportStatus
	ReviewerID  *int64
	ReviewedAt  *time.Time
	ReviewNote  *string
	CreatedAt   time.Time
}

type StatReport struct {
	ID             int64
	SittingID      int64
	Q1             pgtype.Numeric
	Q2             pgtype.Numeric
	Q3             pgtype.Numeric
	Q4             pgtype.Numeric
	Average        pgtype.Numeric
	MaxScore       pgtype.Numeric
	Note           *string
	Nickname       string
	ContributorID  int64
	Source         StatSource
	SourceReportID *int64
	HiddenAt       *time.Time
	HiddenBy       *int64
	HiddenReason   *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UploadIntent struct {
	FileKey   string
	CreatedAt time.Time
}

type User struct {
	ID            int64
	Email         *string
	DisplayName   *string
	IsAdmin       bool
	College       *string
	AdmissionYear *int16
	LastIp        *netip.Addr
	SessionEpoch  int32
	CreatedAt     time.Time
	LastSeenAt    *time.Time
	DeletedAt     *time.Time
}

type VSittingDifficulty struct {
	SittingID     int64
	VoteCount     int64
	AverageRating pgtype.Numeric
	Rating1       int64
	Rating2       int64
	Rating3       int64
	Rating4       int64
	Rating5       int64
}

type VSittingVoting struct {
	SittingID int64
	State     string
}

type Vote struct {
	ID        int64
	SittingID int64
	UserID    int64
	Rating    int16
	CreatedAt time.Time
	UpdatedAt time.Time
}

type VotingRequest struct {
	ID         int64
	SittingID  int64
	UserID     int64
	Note       *string
	Status     VotingRequestStatus
	CreatedAt  time.Time
	ResolvedAt *time.Time
	ResolvedBy *int64
}
