// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package dbq

import (
	"context"
)

const listAssessmentKinds = `-- name: ListAssessmentKinds :many
SELECT id, code, label_ko, label_format, numbered, max_number, sort_order
FROM assessment_kinds
WHERE is_active
ORDER BY sort_order
`

type ListAssessmentKindsRow struct {
	ID          int16
	Code        string
	LabelKo     string
	LabelFormat string
	Numbered    bool
	MaxNumber   *int16
	SortOrder   int16
}

func (q *Queries) ListAssessmentKinds(ctx context.Context) ([]ListAssessmentKindsRow, error) {
	rows, err := q.db.Query(ctx, listAssessmentKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssessmentKindsRow
	for rows.Next() {
		var i ListAssessmentKindsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LabelKo,
			&i.LabelFormat,
			&i.Numbered,
			&i.MaxNumber,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColleges = `-- name: ListColleges :many
SELECT name, sort_order
FROM colleges
WHERE is_active
ORDER BY sort_order
`

type ListCollegesRow struct {
	Name      string
	SortOrder int16
}

func (q *Queries) ListColleges(ctx context.Context) ([]ListCollegesRow, error) {
	rows, err := q.db.Query(ctx, listColleges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollegesRow
	for rows.Next() {
		var i ListCollegesRow
		if err := rows.Scan(&i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
