// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbq

import (
	"context"
	"net/netip"
)

const bumpSessionEpoch = `-- name: BumpSessionEpoch :one
UPDATE users SET session_epoch = session_epoch + 1
WHERE id = $1 AND deleted_at IS NULL
RETURNING session_epoch
`

func (q *Queries) BumpSessionEpoch(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, bumpSessionEpoch, id)
	var session_epoch int32
	err := row.Scan(&session_epoch)
	return session_epoch, err
}

const deleteUserFavorites = `-- name: DeleteUserFavorites :exec
DELETE FROM favorites WHERE user_id = $1
`

func (q *Queries) DeleteUserFavorites(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserFavorites, userID)
	return err
}

const getLiveUser = `-- name: GetLiveUser :one
SELECT id, email, display_name, is_admin, college, admission_year, last_ip, session_epoch, created_at, last_seen_at, deleted_at, google_sub FROM users WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLiveUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getLiveUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.College,
		&i.AdmissionYear,
		&i.LastIp,
		&i.SessionEpoch,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.GoogleSub,
	)
	return i, err
}

const getLiveUserByEmail = `-- name: GetLiveUserByEmail :one
SELECT id, email, display_name, is_admin, college, admission_year, last_ip, session_epoch, created_at, last_seen_at, deleted_at, google_sub FROM users WHERE email = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetLiveUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getLiveUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.College,
		&i.AdmissionYear,
		&i.LastIp,
		&i.SessionEpoch,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.GoogleSub,
	)
	return i, err
}

const getLiveUserBySub = `-- name: GetLiveUserBySub :one
SELECT id, email, display_name, is_admin, college, admission_year, last_ip, session_epoch, created_at, last_seen_at, deleted_at, google_sub FROM users WHERE google_sub = $1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) GetLiveUserBySub(ctx context.Context, googleSub *string) (User, error) {
	row := q.db.QueryRow(ctx, getLiveUserBySub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.College,
		&i.AdmissionYear,
		&i.LastIp,
		&i.SessionEpoch,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.GoogleSub,
	)
	return i, err
}

const insertActivityLog = `-- name: InsertActivityLog :exec
INSERT INTO activity_logs (user_id, action, metadata, ip)
VALUES ($1, $2, $3, $4)
`

type InsertActivityLogParams struct {
	UserID   *int64
	Action   ActivityAction
	Metadata []byte
	Ip       *netip.Addr
}

func (q *Queries) InsertActivityLog(ctx context.Context, arg InsertActivityLogParams) error {
	_, err := q.db.Exec(ctx, insertActivityLog,
		arg.UserID,
		arg.Action,
		arg.Metadata,
		arg.Ip,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, google_sub, display_name, last_ip, last_seen_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, email, display_name, is_admin, college, admission_year, last_ip, session_epoch, created_at, last_seen_at, deleted_at, google_sub
`

type InsertUserParams struct {
	Email       *string
	GoogleSub   *string
	DisplayName *string
	LastIp      *netip.Addr
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.GoogleSub,
		arg.DisplayName,
		arg.LastIp,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.College,
		&i.AdmissionYear,
		&i.LastIp,
		&i.SessionEpoch,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.GoogleSub,
	)
	return i, err
}

const isActiveCollege = `-- name: IsActiveCollege :one
SELECT EXISTS (SELECT 1 FROM colleges WHERE name = $1 AND is_active)
`

func (q *Queries) IsActiveCollege(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveCollege, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockSignIn = `-- name: LockSignIn :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 7201))
`

// Serialises sign-ins that could touch the same rows (same sub or email).
func (q *Queries) LockSignIn(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockSignIn, key)
	return err
}

const recordSignIn = `-- name: RecordSignIn :one
UPDATE users
SET email = $1,
    google_sub = COALESCE(google_sub, $2),
    last_ip = $3,
    last_seen_at = now()
WHERE id = $4
RETURNING id, email, display_name, is_admin, college, admission_year, last_ip, session_epoch, created_at, last_seen_at, deleted_at, google_sub
`

type RecordSignInParams struct {
	Email     *string
	GoogleSub *string
	LastIp    *netip.Addr
	ID        int64
}

// The display name is kept as first stored; only a missing sub is filled in.
func (q *Queries) RecordSignIn(ctx context.Context, arg RecordSignInParams) (User, error) {
	row := q.db.QueryRow(ctx, recordSignIn,
		arg.Email,
		arg.GoogleSub,
		arg.LastIp,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.College,
		&i.AdmissionYear,
		&i.LastIp,
		&i.SessionEpoch,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.GoogleSub,
	)
	return i, err
}

const releaseEmail = `-- name: ReleaseEmail :exec
UPDATE users SET email = NULL WHERE id = $1
`

func (q *Queries) ReleaseEmail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseEmail, id)
	return err
}

const scrubUser = `-- name: ScrubUser :execrows
UPDATE users
SET email = NULL, google_sub = NULL, display_name = NULL, college = NULL,
    admission_year = NULL, last_ip = NULL, is_admin = false,
    deleted_at = now(), session_epoch = session_epoch + 1
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ScrubUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, scrubUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastSeen = `-- name: TouchLastSeen :exec
UPDATE users SET last_seen_at = now()
WHERE id = $1 AND (last_seen_at IS NULL OR last_seen_at < now() - interval '10 minutes')
`

func (q *Queries) TouchLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchLastSeen, id)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users
SET college = CASE WHEN $1::boolean THEN $2 ELSE college END,
    admission_year = CASE WHEN $3::boolean THEN $4 ELSE admission_year END
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, email, display_name, is_admin, college, admission_year, last_ip, session_epoch, created_at, last_seen_at, deleted_at, google_sub
`

type UpdateProfileParams struct {
	SetCollege       bool
	College          *string
	SetAdmissionYear bool
	AdmissionYear    *int16
	ID               int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.SetCollege,
		arg.College,
		arg.SetAdmissionYear,
		arg.AdmissionYear,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.IsAdmin,
		&i.College,
		&i.AdmissionYear,
		&i.LastIp,
		&i.SessionEpoch,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.DeletedAt,
		&i.GoogleSub,
	)
	return i, err
}
